language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.3
    - php: hhvm
    - php: nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
